name: "Publish openscad file to playground"
description: "Hosts an openscad file using openscad-playgound"
author: "Bob van der Vuurst"

inputs:
  filename:
    description: "Openscad filename"
    required: true
    default: "test-file.scad"
  libraries:
    description: "JSON file with included libraries"
    required: false
    default: ''

outputs:
  page_url:
    description: "url of github pages deployment"
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Set up Docker
      uses: docker/setup-docker-action@v4
    - name: Clone openscad playground
      run: git clone -b dev https://github.com/Bob-vdV/openscad-playground.git playground
      shell: bash
    - name: Copy openscad file
      run: cp ${{ inputs.filename }} playground/public/playground.scad
      shell: bash
    - name: Replace default libraries
      if: ${{ inputs.libraries != '' }}
      run: cp ${{ inputs.libraries }} playground/libs-config.json
      shell: bash
    - name: Build static content
      working-directory: playground
      run: |
        npm install
        npm run build:all
      shell: bash
    - name: Upload artifact
      if: !inputs.dry-run 
      uses: actions/upload-pages-artifact@v4
      with:
        path: 'playground/dist'
    - name: Deploy to GitHub Pages
      if: !inputs.dry-run
      id: deployment
      uses: actions/deploy-pages@v4
