name: "Hello"

on:
  push:
    branches: ["actions"]
  workflow_dispatch: 
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          filename: "t2.scad"
